devices:
  - name: 'Virgin Router'
    mac: '18:35:D1:CB:A5:C8'
    ip: '192.168.0.1'
    alive: false
    allowed: 1
  - name: 'Pi Cluster 2'
    mac: 'B8:27:EB:27:37:62'
    ip: '192.168.0.11'
    alive: false
    allowed: 1
  - name: 'Pi Cluster 2'
    mac: '00:DB:DF:A2:2E:CA'
    ip: '192.168.0.15'
    alive: false
    allowed: 1
  - name: 'Nintendo Switch'
    mac: 'B8:8A:EC:C5:31:95'
    ip: '192.168.0.18'
    alive: false
    allowed: 1
  - name: 'Ubuntu Laptop'
    mac: 'D4:25:8B:47:59:C8'
    ip: '192.168.0.21'
    alive: false
    allowed: 1
  - name: 'Printer'
    mac: 'BC:E9:2F:AD:24:41'
    ip: '192.168.0.25'
    alive: false
    allowed: 1
  - name: 'YJ Tablet'
    mac: '74:EB:80:80:0D:FO'
    ip: '192.168.0.27'
    alive: false
    allowed: 1
  - name: 'YJ Phone'
    mac: '28:C2:1F:1E:A1:53'
    ip: '192.168.0.29'
    alive: false
    allowed: 1
  - name: 'Main TV'
    mac: 'BC:7E:8B:90:0B:73'
    ip: '192.168.0.34'
    alive: false
    allowed: 1
  - name: 'Pi Cluster 1'
    mac: 'B8:27:EB:1A:F1:F3'
    ip: '192.168.0.38'
    alive: false
    allowed: 1
  - name: 'Pi Plex'
    mac: 'E4:5F:01:12:FF:13'
    ip: '192.168.0.42'
    alive: false
    allowed: 1
  - name: 'Simon Samsung Flip'
    mac: 'EE:7F:9F:71:51:66'
    ip: '192.168.0.47'
    alive: false
    allowed: 1